name: RiftEvent2
version: '${project.version}'
main: RiftEvent2.RiftEvent2
api-version: '1.20'
authors: [ Jbeast291 ]
depend: [Citizens]
commands:
  riftevent:
    description: Rift-Event Command
    permission: riftevent.admin